import {
  Globe,
  Code,
  FileText,
  Link,
  Search,
  Smartphone,
  Type,
  Users,
  Eye,
  Key,
  Binary,
  Tag,
  Settings,
  Database,
  Network,
  Router,
  Wifi,
  MapPin,
  Shield,
} from 'lucide-react';

export const WEB_ROUTES = {
  URL_ENCODER_DECODER: '/url-encoder-decoder',
  HTML_ENTITIES: '/html-entities',
  URL_PARSER: '/url-parser',
  DEVICE_INFO: '/device-info',
  BASIC_AUTH_GENERATOR: '/basic-auth-generator',
  OPEN_GRAPH_GENERATOR: '/open-graph-generator',
  OTP_CODE_GENERATOR: '/otp-code-generator',
  MIME_TYPES: '/mime-types',
  JWT_PARSER: '/jwt-parser',
  KEYCODE_INFO: '/keycode-info',
  UNICODE_CHAR_CODES: '/unicode-char-codes',
  HTML_WYSIWYG_EDITOR: '/html-wysiwyg-editor',
  USER_AGENT_PARSER: '/user-agent-parser',
  HTTP_STATUS_CODES: '/http-status-codes',
  JSON_DIFF: '/json-diff',
  IPV4_NETWORK_CALCULATOR: '/ipv4-network-calculator',
  IPV4_ADDRESS_CONVERTER: '/ipv4-address-converter',
  IPV4_RANGE_EXPANDER: '/ipv4-range-expander',
  MAC_ADDRESS_LOOKUP: '/mac-address-lookup',
  MAC_ADDRESS_GENERATOR: '/mac-address-generator',
  IPV6_ULA_GENERATOR: '/ipv6-ula-generator',
};

export const webNavigationConfig = {
  titleKey: 'web',
  url: '#',
  icon: Globe,
  items: [
    {
      titleKey: 'urlEncoderDecoder',
      url: WEB_ROUTES.URL_ENCODER_DECODER,
      icon: Link,
    },
    {
      titleKey: 'htmlEntities',
      url: WEB_ROUTES.HTML_ENTITIES,
      icon: Code,
    },
    {
      titleKey: 'urlParser',
      url: WEB_ROUTES.URL_PARSER,
      icon: Search,
    },
    {
      titleKey: 'deviceInfo',
      url: WEB_ROUTES.DEVICE_INFO,
      icon: Smartphone,
    },
    {
      titleKey: 'basicAuthGenerator',
      url: WEB_ROUTES.BASIC_AUTH_GENERATOR,
      icon: Key,
    },
    {
      titleKey: 'openGraphGenerator',
      url: WEB_ROUTES.OPEN_GRAPH_GENERATOR,
      icon: Tag,
    },
    {
      titleKey: 'otpCodeGenerator',
      url: WEB_ROUTES.OTP_CODE_GENERATOR,
      icon: Binary,
    },
    {
      titleKey: 'mimeTypes',
      url: WEB_ROUTES.MIME_TYPES,
      icon: FileText,
    },
    {
      titleKey: 'jwtParser',
      url: WEB_ROUTES.JWT_PARSER,
      icon: Settings,
    },
    {
      titleKey: 'keycodeInfo',
      url: WEB_ROUTES.KEYCODE_INFO,
      icon: Type,
    },
    {
      titleKey: 'htmlWysiwygEditor',
      url: WEB_ROUTES.HTML_WYSIWYG_EDITOR,
      icon: Eye,
    },
    {
      titleKey: 'userAgentParser',
      url: WEB_ROUTES.USER_AGENT_PARSER,
      icon: Users,
    },
    {
      titleKey: 'httpStatusCodes',
      url: WEB_ROUTES.HTTP_STATUS_CODES,
      icon: Database,
    },
    {
      titleKey: 'jsonDiff',
      url: WEB_ROUTES.JSON_DIFF,
      icon: Search,
    },
    {
      titleKey: 'ipv4NetworkCalculator',
      url: WEB_ROUTES.IPV4_NETWORK_CALCULATOR,
      icon: Network,
    },
    {
      titleKey: 'ipv4AddressConverter',
      url: WEB_ROUTES.IPV4_ADDRESS_CONVERTER,
      icon: Router,
    },
    {
      titleKey: 'ipv4RangeExpander',
      url: WEB_ROUTES.IPV4_RANGE_EXPANDER,
      icon: Wifi,
    },
    {
      titleKey: 'macAddressLookup',
      url: WEB_ROUTES.MAC_ADDRESS_LOOKUP,
      icon: MapPin,
    },
    {
      titleKey: 'macAddressGenerator',
      url: WEB_ROUTES.MAC_ADDRESS_GENERATOR,
      icon: Shield,
    },
    {
      titleKey: 'ipv6UlaGenerator',
      url: WEB_ROUTES.IPV6_ULA_GENERATOR,
      icon: Network,
    },
  ],
};
